services:
  - type: web
    name: coo-mail-forge
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python serve.py"
    envVars:
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: DISABLE_SCRAPER
        value: "1"
